# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [16.x]
        os: ["windows-latest", "windows-2019", "windows-2016"]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Print dir contents
      run: |
       ls -ahltr ${{ github.workspace }}
       pwd
    - name: Cache build folder
      uses: pdotl/cache@main
      with:
        key: cs-repo-${{ github.run_number }}-${{ github.run_attempt }}
        path: "."
    - run: npm ci
