# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [16.x]
        os: ["windows-latest", "macos-latest", "ubuntu-latest", "self-hosted"]
    steps:
    - uses: actions/checkout@v3
    - name: Print versions
      run: |
       tar --version
    - name: Cache build folder
      uses: pdotl/cache@ae36abc5f1b4e0315f66d135ac060e6b685f7ef8
      with:
        key: cs-repo-${{ github.run_number }}-${{ github.run_attempt }}
        path: "."
        enableCrossOsArchive: true
