# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [16.x]
        os: ["windows-latest", "macos-latest", "ubuntu-latest"]
    steps:
    - uses: actions/checkout@v3
    - name: Print versions
      run: |
       zstd -q --version
       zstd --quiet --version
       zstd --version --quiet
       zstd -Vq
    - name: Cache build folder
      uses: pdotl/cache@6f0a8cf36564519cb226a183601cabc805b624ad
      with:
        key: cs-repo-${{ github.run_number }}-${{ github.run_attempt }}
        path: "."
        enableCrossOsArchive: true
