# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master", "hackathon-steps-output" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
      id: checkout
    - name: Use Node.js ${{ matrix.node-version }}
      id: node-setup
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Print dir contents
      id: print
      run: |
       ls -ahltr ${{ github.workspace }}
    - name: Cache build folder
      uses: pdotl/cache@5fd066637a8f8e5608f61fa84328d1b6106a978e
      id: Cache
      with:
        key: cs-repo-${{ github.run_number }}-${{ github.run_attempt }}
        path: "."
    - run: npm ci
      id: ci
    - name: Dump steps context
      run: echo ${{ toJSON(steps) }}
    - name: Test bts
      id: bts
      uses: pdotl/bts
        content: ${{ toJSON(steps) }}